config:
  install_tree:
    root: /cvmfs/sw.hsf.org/spackages2
    projections:
      all: ${PACKAGE}/${VERSION}-${HASH}/${target}-${os}-${COMPILERNAME}${COMPILERVER}-opt
      build_type=Debug: ${PACKAGE}/${VERSION}-${HASH}/${target}-${os}-${COMPILERNAME}${COMPILERVER}-dbg
  module_roots:
    lmod: /cvmfs/sw.hsf.org/spackages/modules
    tcl: /cvmfs/sw.hsf.org/spackages/modules
