name: k4CITests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sw.hsf.org,sw-nightlies.hsf.org,sft-nightlies.cern.ch,sft.cern.ch,geant4.cern.ch'
    - name: Start container
      run: |
        docker run -it --name CI_container -e GITHUB_ENV=${GITHUB_ENV}  -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs:shared -d clicdp/cc7-lcg /bin/bash
    - name: Setup container
      run: |
        docker exec CI_container /bin/bash -c " ln -s /usr/lib64/liblzma.so.5.2.2 /usr/lib64/liblzma.so;"

    - name: Setup Spack
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\
        curl -L -o spack.tar.gz https://gitlab.cern.ch/key4hep/k4-deploy/-/jobs/artifacts/release/raw/key4hep-spack_centos7-cvmfs.tar.gz?job=setup_spack_push;\
        tar xfz spack.tar.gz && rm spack.tar.gz;'
    - name: Concretize
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\
        source spack/share/spack/setup-env.sh;\
        spack spec -I key4hep-stack | tee -a key4hep-stack-concretization.log;\
        export KCON=$(cat key4hep-stack-concretization.log);\
        echo "action_state=yellow" >> $GITHUB_ENV;\
        echo "KCON=${KCON}" >> $GITHUB_ENV;' 
    - name: Prepare Env Vars for comment
      run: |
        export KCON=$(cat key4hep-stack-concretization.log);\
        echo "action_state=yellow" >> $GITHUB_ENV;\
        echo "KCON=${KCON}" >> $GITHUB_ENV;' 
    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: "${{ env.action_state }}" });
          github.issues.createComment({ issue_number, owner, repo, body: "${{ env.KCON }}" });

